@tool
extends EditorScript

# Track 6 sub-task 3b — auto-exports SpellDefinitions.ALL to a TOML file
# the server can consume. Mirrors the items.toml / zone_camps.toml
# pattern. Single source of truth stays in data/spell_definitions.gd;
# this tool round-trips the server-relevant subset.
#
# How to run:
#   1. Open this script in the Godot editor (File → Open).
#   2. File → Run (Ctrl+Shift+X).
#   3. Check the output panel for the "Wrote N spells to..." line.
#   4. Copy / commit the generated file at the server-side path below.
#
# Output path: writes to the absolute filesystem path so the server
# repo gets the fresh data without needing both repos open in Godot.
# Adjust OUTPUT_PATH if your server lives elsewhere.

const OUTPUT_PATH := "F:/Projects/server/crates/projectdawn-server/data/spells.toml"

# Fields the server cares about for sub-task 3b damage / heal
# processing. Buff / HoT / DoT / CC / port / song fields are
# intentionally excluded — those stay client-side until sub-task 4
# lifts buff state server-side. The server's CastSpell handler
# ignores spells whose target_type isn't in the supported set.
const SERVER_FIELDS := [
	"name", "target_type", "damage_type", "base_damage", "heal_amount",
	"mana_cost", "hp_cost", "cast_time", "cooldown", "aoe_radius",
	"min_level", "classes",
]

const SUPPORTED_TARGET_TYPES := ["ENEMY", "SELF", "AOE", "NONE"]

func _run() -> void:
	var spells: Array = SpellDefinitions.ALL
	var lines: PackedStringArray = []
	lines.append("# AUTO-GENERATED by Project_Dawn/tools/export_spells.gd")
	lines.append("# Edit data/spell_definitions.gd and re-run the tool;")
	lines.append("# do NOT edit this file by hand.")
	lines.append("")

	var written := 0
	var skipped := 0
	for entry: Dictionary in spells:
		var target_type: String = entry.get("target_type", "NONE")
		# Skip target types the server doesn't yet process. They still
		# work client-side; this just tells the server not to bother
		# with them.
		if target_type not in SUPPORTED_TARGET_TYPES:
			skipped += 1
			continue
		lines.append("[[spell]]")
		for key in SERVER_FIELDS:
			if not entry.has(key):
				continue
			lines.append("%s = %s" % [key, _toml_value(entry[key])])
		lines.append("")
		written += 1

	var f := FileAccess.open(OUTPUT_PATH, FileAccess.WRITE)
	if f == null:
		push_error("export_spells: could not open %s for writing (err %d)" % [OUTPUT_PATH, FileAccess.get_open_error()])
		return
	for line in lines:
		f.store_line(line)
	f.close()
	print("export_spells: wrote %d spells to %s (skipped %d non-server target types)" % [written, OUTPUT_PATH, skipped])

func _toml_value(v: Variant) -> String:
	# Minimal TOML emitter — handles the subset of types
	# spell_definitions.gd uses.
	match typeof(v):
		TYPE_STRING:
			return "\"" + (v as String).replace("\\", "\\\\").replace("\"", "\\\"") + "\""
		TYPE_INT:
			return str(v)
		TYPE_FLOAT:
			# Ensure trailing .0 so the toml crate parses as float.
			var s := str(v)
			if not "." in s and not "e" in s.to_lower():
				s += ".0"
			return s
		TYPE_BOOL:
			return "true" if v else "false"
		TYPE_ARRAY, TYPE_PACKED_STRING_ARRAY:
			var parts: PackedStringArray = []
			for elem in v:
				parts.append(_toml_value(elem))
			return "[" + ", ".join(parts) + "]"
	push_error("export_spells: unsupported TOML type %s for value %s" % [typeof(v), v])
	return "null"
